name: Hello Ayman

on:
  push:

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install depencies
        run: npm install

      - name: Build
        run: npm run build